### PR TITLE
Bring in improvements

### PR DESCRIPTION
**Pull request by aaronpdennis**
Merge improvements from @JoshData to a new branch focused on changing to only one tile source that includes both boundaries and labels.

See #1 for original PR.

### CODE REVIEW

**Comment by aaronpdennis** [comment]
@JoshData I'm going to bring in your improvements on this branch. Next, I want to change a few things about the tiling process and upload so that labels and boundaries will be in a single Mapbox tileset. This is important because when tilesets are updated (like for the next Congress) the labels tileset is processed by Mapbox way faster than the district boundaries tileset, leaving any live web maps using tile sources mismatched until Mapbox's services catch up (~ 30 min).

**Comment by JoshData** [comment]
Don't let the perfect be the enemy of the good. :)

One file is better than two, to make things simpler, but there's also something nice about having a tileset that is _just_ district boundaries without any extra stuff used only for rendering. It probably makes querying the API slightly easier.

Also one of my changes was to have the output files named w/ "114_2015" so that they self-identify as for the 114th Congress using the 2015 Census TIGER release. That helps work around the issue you're raising.

**Comment by aaronpdennis** [comment]
@JoshData Good advice, to be sure. Looks like it won't be worth the trouble, I was hoping to generate one `.mbtiles` file from Tippecanoe, but Tippecanoe's simplification process drops the label points. And as you point out, the naming conventions addresses the concern about updates.

I'm going to make some small changes to the `mapbox-style-template.json` and the district specific filtering on the example map and then I'll merge this with the gh-pages branch.

**Comment by JoshData** [comment]
Now that I have this deployed (just in GovTrack's iframe widget, so it doesn't actually appear anywhere on GovTrack itself yet), it looks like Mapbox does billing based on tileset requests -- so having the map split across two tilesets (boundaries, labels) counts against account limits twice. (Your style also has streets and terrain, so it looks like it comes out to four map requests per user.) So, nevermind what I said about it being nice to have it in two files - I take that back. If we can merge the tilesets, and if I drop terrain, then I'd double what can be displayed under the account limits.

On the other hand, to deploy throughout GovTrack I'd fall between Mapbox's standard and premium limits anyway, which means I'm going to need to ask for special treatment anyway to be able to afford it.

**Pull request merged**
